-- Create Companies table
CREATE TABLE Companies (
    company_id SERIAL PRIMARY KEY,
    company_name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by VARCHAR(30) DEFAULT CURRENT_USER NOT NULL,
    updated_by VARCHAR(30) DEFAULT CURRENT_USER NOT NULL
);