CREATE TABLE Ratings (
    rating_id SERIAL PRIMARY KEY,
    nickname VARCHAR(30) NOT NULL,
    game_id INTEGER NOT NULL,
    score NUMERIC(3,2) NOT NULL CHECK (score BETWEEN 0 AND 5),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by VARCHAR(30) DEFAULT CURRENT_USER NOT NULL,
    updated_by VARCHAR(30) DEFAULT CURRENT_USER NOT NULL,
    CONSTRAINT fk_ratings_game FOREIGN KEY (game_id) REFERENCES Videogames(game_id)
);